import { describe, expect, it } from 'vitest'
import { REGIONS } from './regions'

describe('static region map', () => {
  it('contains The Forge with its canonical id', () => {
    expect(REGIONS.find((r) => r.name === 'The Forge')?.id).toBe(10000002)
  })

  it('is sorted by name and k-space only', () => {
    const names = REGIONS.map((r) => r.name)
    expect(names).toEqual([...names].sort((a, b) => a.localeCompare(b)))
    expect(REGIONS.every((r) => r.id < 11000000)).toBe(true)
  })

  it('carries no duplicate id and no duplicate name', () => {
    // regions.ts is regenerated by hand, so a copy-paste during a CCP region addition
    // is the realistic way it breaks. A duplicate id makes the REGION_NAMES map in
    // format.ts silently keep whichever entry it saw last, so one region renders under
    // another's name — and the coverage sentence, which exists precisely to stop the
    // UI making confident claims about regions, becomes the thing making the false one.
    // Sizes are compared rather than membership: a set that merely CONTAINS every id
    // says nothing about how many rows collapsed into it (TEST-25).
    expect(new Set(REGIONS.map((r) => r.id)).size).toBe(REGIONS.length)
    expect(new Set(REGIONS.map((r) => r.name)).size).toBe(REGIONS.length)
  })
})
