global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi-app'
    scrape_interval: 5s
    # This target assumes the FastAPI app is running on the host machine.
    # 'host.docker.internal' is a special DNS name that resolves to the host's IP from within a Docker container.
    static_configs:
      - targets: ['host.docker.internal:8000']
