/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_auth_sso_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_sso_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_sso_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Public Contracts
         * @description Retrieves a paginated list of contracts based on specified filters.
         *
         *     This endpoint uses a service layer to apply advanced filtering, sorting,
         *     and pagination to public contracts.
         */
        get: operations["list_public_contracts_contracts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract
         * @description Retrieves a single contract by its ID, including its items.
         */
        get: operations["get_contract_contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notification Settings */
        get: operations["get_notification_settings_me_notification_settings_get"];
        /** Update Notification Settings */
        put: operations["update_notification_settings_me_notification_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_me_notifications__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/mark-all-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_me_notifications_mark_all_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/{notification_id}/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_me_notifications__notification_id__mark_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved-searches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Searches */
        get: operations["list_saved_searches_me_saved_searches__get"];
        put?: never;
        /** Create Saved Search */
        post: operations["create_saved_search_me_saved_searches__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved-searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename Saved Search */
        put: operations["rename_saved_search_me_saved_searches__search_id__put"];
        post?: never;
        /** Delete Saved Search */
        delete: operations["delete_saved_search_me_saved_searches__search_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/watchlist-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist Items */
        get: operations["list_watchlist_items_me_watchlist_items__get"];
        put?: never;
        /** Add Watchlist Item */
        post: operations["add_watchlist_item_me_watchlist_items__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/watchlist-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Watchlist Item */
        put: operations["update_watchlist_item_me_watchlist_items__item_id__put"];
        post?: never;
        /** Delete Watchlist Item */
        delete: operations["delete_watchlist_item_me_watchlist_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContractItemSchema
         * @description Schema for an item within a contract.
         */
        ContractItemSchema: {
            /** Category */
            category?: string | null;
            /** Is Blueprint Copy */
            is_blueprint_copy?: boolean | null;
            /** Is Included */
            is_included: boolean;
            /** Is Singleton */
            is_singleton: boolean;
            /** Market Group Id */
            market_group_id?: number | null;
            /** Quantity */
            quantity: number;
            /** Raw Quantity */
            raw_quantity?: number | null;
            /** Record Id */
            record_id: number;
            /** Type Id */
            type_id: number;
            /** Type Name */
            type_name?: string | null;
        };
        /**
         * ContractSchema
         * @description Schema for a public contract.
         */
        ContractSchema: {
            /** Contract Id */
            contract_id: number;
            /** Date Completed */
            date_completed?: string | null;
            /**
             * Date Expired
             * Format: date-time
             */
            date_expired: string;
            /**
             * Date Issued
             * Format: date-time
             */
            date_issued: string;
            /** End Location Id */
            end_location_id?: number | null;
            /** For Corporation */
            for_corporation: boolean;
            /** Is Ship Contract */
            is_ship_contract: boolean;
            /** Issuer Corporation Id */
            issuer_corporation_id: number;
            /** Issuer Corporation Name */
            issuer_corporation_name?: string | null;
            /** Issuer Id */
            issuer_id: number;
            /** Issuer Name */
            issuer_name?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ContractItemSchema"][];
            /** Price */
            price?: number | null;
            /** Reward */
            reward?: number | null;
            /** Start Location Id */
            start_location_id: number;
            /** Start Location Name */
            start_location_name?: string | null;
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
            /** Type */
            type: string;
            /** Volume */
            volume?: number | null;
        };
        /** CurrentUserSchema */
        CurrentUserSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
        };
        /**
         * ErrorDetail
         * @description The FastAPI HTTPException / JSONResponse error body shape ({"detail": ...}),
         *     declared so the login/callback 400 and 503 responses carry their real JSON
         *     body in the OpenAPI contract instead of an empty one.
         */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NotificationSchema */
        NotificationSchema: {
            /** Contract Id */
            contract_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Read */
            is_read: boolean;
            /** Message */
            message: string;
            /** Price */
            price?: number | null;
            /** Type */
            type: string;
            /** Watch Type Id */
            watch_type_id?: number | null;
        };
        /** NotificationSettingsSchema */
        NotificationSettingsSchema: {
            /** Watchlist Alerts Enabled */
            watchlist_alerts_enabled: boolean;
        };
        /** PaginatedResponse[ContractSchema] */
        PaginatedResponse_ContractSchema_: {
            /**
             * Items
             * @description List of items for the current page
             */
            items: components["schemas"]["ContractSchema"][];
            /**
             * Page
             * @description Current page number
             */
            page: number;
            /**
             * Size
             * @description Number of items per page
             */
            size: number;
            /**
             * Total
             * @description Total number of items
             */
            total: number;
        };
        /** PaginatedResponse[NotificationSchema] */
        PaginatedResponse_NotificationSchema_: {
            /**
             * Items
             * @description List of items for the current page
             */
            items: components["schemas"]["NotificationSchema"][];
            /**
             * Page
             * @description Current page number
             */
            page: number;
            /**
             * Size
             * @description Number of items per page
             */
            size: number;
            /**
             * Total
             * @description Total number of items
             */
            total: number;
        };
        /** SavedSearchCreate */
        SavedSearchCreate: {
            /** Name */
            name: string;
            search_parameters: components["schemas"]["SavedSearchParameters"];
        };
        /**
         * SavedSearchParameters
         * @description Server-side validation model for a saved search's stored filter blob. Mirrors the
         *     frontend ContractSearch shape minus `page`; extra="forbid" rejects the inert ME/TE params
         *     (FASTAPI-2), the wire-only `is_ship_contract`, `page`, and arbitrary junk (design §4.5).
         */
        SavedSearchParameters: {
            /** Is Bpc */
            is_bpc?: boolean | null;
            /** Max Price */
            max_price?: number | null;
            /** Min Price */
            min_price?: number | null;
            /** Region Ids */
            region_ids?: number[] | null;
            /** Search */
            search?: string | null;
            /**
             * Ships Only
             * @default true
             */
            ships_only: boolean;
            /**
             * Size
             * @default 50
             */
            size: number;
            /** @default date_issued */
            sort_by: components["schemas"]["SortableContractFields"];
            /** @default desc */
            sort_direction: components["schemas"]["SortDirection"];
        };
        /** SavedSearchSchema */
        SavedSearchSchema: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            search_parameters: components["schemas"]["SavedSearchParameters"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SavedSearchUpdate */
        SavedSearchUpdate: {
            /** Name */
            name: string;
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: "asc" | "desc";
        /**
         * SortableContractFields
         * @description Fields that can be used for sorting contracts.
         * @enum {string}
         */
        SortableContractFields: "date_issued" | "date_expired" | "price" | "collateral" | "ship_name" | "volume";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchlistItemCreate
         * @description Add-watchlist body: exactly one of type_id / type_name, plus optional max_price / notes.
         */
        WatchlistItemCreate: {
            /**
             * Max Price
             * @description ISK; >= 0.01 when present.
             */
            max_price?: number | null;
            /** Notes */
            notes?: string | null;
            /** Type Id */
            type_id?: number | null;
            /** Type Name */
            type_name?: string | null;
        };
        /** WatchlistItemSchema */
        WatchlistItemSchema: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Max Price */
            max_price?: number | null;
            /** Notes */
            notes?: string | null;
            /** Type Id */
            type_id: number;
            /** Type Name */
            type_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WatchlistItemUpdate
         * @description Partial update: omitted field preserves, explicit JSON null clears (via model_fields_set).
         */
        WatchlistItemUpdate: {
            /** Max Price */
            max_price?: number | null;
            /** Notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_auth_sso_callback_get: {
        parameters: {
            query?: {
                state?: string | null;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SSO state/browser-binding mismatch. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description EVE SSO is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    login_auth_sso_login_get: {
        parameters: {
            query?: {
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description EVE SSO is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    logout_auth_sso_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_public_contracts_contracts__get: {
        parameters: {
            query?: {
                /** @description Case-insensitive search across contract title and ship name. */
                search?: string | null;
                /** @description Minimum price. */
                min_price?: number | null;
                /** @description Maximum price. */
                max_price?: number | null;
                /** @description Minimum collateral. */
                min_collateral?: number | null;
                /** @description Maximum collateral. */
                max_collateral?: number | null;
                /** @description Minimum runs for BPCs (-1 for original). */
                min_runs?: number | null;
                /** @description Maximum runs for BPCs. */
                max_runs?: number | null;
                /** @description Minimum Material Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                min_me?: number | null;
                /** @description Maximum Material Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                max_me?: number | null;
                /** @description Minimum Time Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                min_te?: number | null;
                /** @description Maximum Time Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                max_te?: number | null;
                /** @description List of region IDs to filter by. */
                region_ids?: number[] | null;
                /** @description List of solar system IDs to filter by. */
                system_ids?: number[] | null;
                /** @description List of station IDs to filter by. */
                station_ids?: number[] | null;
                /** @description List of ship type IDs to filter by. */
                type_ids?: number[] | null;
                /** @description Filter for contracts containing blueprints (BPCs). */
                is_bpc?: boolean | null;
                /** @description Filter for contracts flagged as ship contracts (contract-level flag). */
                is_ship_contract?: boolean | null;
                /** @description Page number. */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
                /** @description Field to sort by. */
                sort_by?: components["schemas"]["SortableContractFields"];
                /** @description Sort direction. */
                sort_direction?: components["schemas"]["SortDirection"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ContractSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserSchema"];
                };
            };
        };
    };
    get_notification_settings_me_notification_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    update_notification_settings_me_notification_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettingsSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_me_notifications__get: {
        parameters: {
            query?: {
                is_read?: boolean | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_NotificationSchema_"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_me_notifications_mark_all_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    mark_read_me_notifications__notification_id__mark_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_searches_me_saved_searches__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    create_saved_search_me_saved_searches__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"];
                };
            };
            /** @description Per-user saved-search cap reached */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Duplicate saved-search name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_saved_search_me_saved_searches__search_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Saved search not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Duplicate saved-search name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_search_me_saved_searches__search_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Saved search not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_items_me_watchlist_items__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemSchema"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    add_watchlist_item_me_watchlist_items__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemSchema"];
                };
            };
            /** @description Cap reached / unknown name / not a published ship */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Already watching this type */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description ESI unreachable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    update_watchlist_item_me_watchlist_items__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_item_me_watchlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
