/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_auth_sso_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_sso_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_sso_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Public Contracts
         * @description Retrieves a paginated list of contracts based on specified filters.
         *
         *     This endpoint uses a service layer to apply advanced filtering, sorting,
         *     and pagination to public contracts.
         */
        get: operations["list_public_contracts_contracts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Contract Taxonomy
         * @description Retrieves the dogma category and group option lists for the item-level filters,
         *     with a readiness signal saying whether those filters can be trusted yet.
         */
        get: operations["list_contract_taxonomy_contracts_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract
         * @description Retrieves a single contract by its ID, including its items.
         */
        get: operations["get_contract_contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notification Settings */
        get: operations["get_notification_settings_me_notification_settings_get"];
        /** Update Notification Settings */
        put: operations["update_notification_settings_me_notification_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_me_notifications__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/mark-all-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_me_notifications_mark_all_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/{notification_id}/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_me_notifications__notification_id__mark_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved-searches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Searches */
        get: operations["list_saved_searches_me_saved_searches__get"];
        put?: never;
        /** Create Saved Search */
        post: operations["create_saved_search_me_saved_searches__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved-searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename Saved Search */
        put: operations["rename_saved_search_me_saved_searches__search_id__put"];
        post?: never;
        /** Delete Saved Search */
        delete: operations["delete_saved_search_me_saved_searches__search_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/watchlist-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist Items */
        get: operations["list_watchlist_items_me_watchlist_items__get"];
        put?: never;
        /** Add Watchlist Item */
        post: operations["add_watchlist_item_me_watchlist_items__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/watchlist-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Watchlist Item */
        put: operations["update_watchlist_item_me_watchlist_items__item_id__put"];
        post?: never;
        /** Delete Watchlist Item */
        delete: operations["delete_watchlist_item_me_watchlist_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BlueprintSummary
         * @description The blueprint terms of a contract offering copies.
         *
         *     With more than one copy on offer the three value fields are NULL: the terms belong
         *     to individual copies, and picking one to report would misdescribe the others.
         */
        BlueprintSummary: {
            /** Copy Count */
            copy_count: number;
            /** Material Efficiency */
            material_efficiency?: number | null;
            /** Runs */
            runs?: number | null;
            /** Time Efficiency */
            time_efficiency?: number | null;
        };
        /**
         * CompositionCategory
         * @description One category's share of a contract's offered item rows.
         *
         *     `name` is NULL when the taxonomy name cache has not resolved that category yet,
         *     and `category_id` is NULL for the bucket holding rows whose category could not be
         *     determined at all — the client renders that bucket as "other".
         */
        CompositionCategory: {
            /** Category Id */
            category_id?: number | null;
            /** Item Row Count */
            item_row_count: number;
            /** Name */
            name?: string | null;
        };
        /**
         * CompositionSummary
         * @description What a multi-item contract is made of, structured rather than pre-rendered.
         *
         *     Counts are item ROWS, not summed quantities: "3 modules" describes a bundle far
         *     better than "3,000 units of ammunition" does. Pluralization and truncation stay
         *     with the client, which is the layer that knows how much room it has.
         */
        CompositionSummary: {
            /** Categories */
            categories: components["schemas"]["CompositionCategory"][];
            /** Total Item Rows */
            total_item_rows: number;
            /** Total Volume */
            total_volume?: number | null;
        };
        /**
         * ContractDetailSchema
         * @description A single contract with its full item array — REQUESTED items included, because
         *     the detail page shows both sides of the trade.
         */
        ContractDetailSchema: {
            blueprint_summary?: components["schemas"]["BlueprintSummary"] | null;
            /** Buyout */
            buyout?: number | null;
            /** Collateral */
            collateral: number;
            composition?: components["schemas"]["CompositionSummary"] | null;
            /** Contract Id */
            contract_id: number;
            /**
             * Date Expired
             * Format: date-time
             */
            date_expired: string;
            /**
             * Date Issued
             * Format: date-time
             */
            date_issued: string;
            /** Days To Complete */
            days_to_complete?: number | null;
            /** End Location Id */
            end_location_id?: number | null;
            /** End Location Name */
            end_location_name?: string | null;
            /** For Corporation */
            for_corporation: boolean;
            /** Is Blueprint Copy Contract */
            is_blueprint_copy_contract: boolean;
            /** Is Ship Contract */
            is_ship_contract: boolean;
            /** Issuer Corporation Id */
            issuer_corporation_id: number;
            /** Issuer Corporation Name */
            issuer_corporation_name?: string | null;
            /** Issuer Id */
            issuer_id: number;
            /** Issuer Name */
            issuer_name?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ContractItemSchema"][];
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Price */
            price?: number | null;
            /** Primary Label */
            primary_label: string;
            /** Reward */
            reward?: number | null;
            /** Reward Per Volume */
            reward_per_volume?: number | null;
            /** Start Location Id */
            start_location_id?: number | null;
            /** Start Location Name */
            start_location_name?: string | null;
            /** Start Location System Id */
            start_location_system_id?: number | null;
            /** Title */
            title?: string | null;
            /** Type */
            type: string;
            /** Volume */
            volume?: number | null;
        };
        /**
         * ContractItemSchema
         * @description Schema for an item within a contract.
         *
         *     `is_singleton` and `raw_quantity` are deliberately absent. Both are fields of ESI's
         *     AUTHENTICATED character/corporation contract-item routes; the public item route
         *     Hangar Bay reads carries neither, so `is_singleton` is the mapping default and
         *     `raw_quantity` is NULL for every item in the corpus today. The columns stay — they
         *     fill in the moment a user's own contracts are ingested — but a wire field that can
         *     only misinform is worse than no wire field (ESI-3).
         */
        ContractItemSchema: {
            /** Category */
            category?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Group Id */
            group_id?: number | null;
            /** Is Blueprint Copy */
            is_blueprint_copy?: boolean | null;
            /** Is Included */
            is_included: boolean;
            /** Market Group Id */
            market_group_id?: number | null;
            /** Material Efficiency */
            material_efficiency?: number | null;
            /** Quantity */
            quantity: number;
            /** Record Id */
            record_id: number;
            /** Runs */
            runs?: number | null;
            /** Time Efficiency */
            time_efficiency?: number | null;
            /** Type Id */
            type_id: number;
            /** Type Name */
            type_name?: string | null;
        };
        /**
         * ContractListItemSchema
         * @description A contract as it appears in a list row: a summary, carrying no item array.
         *
         *     Everything a client used to derive by walking the items — the blueprint flag, the
         *     headline label, the composition breakdown — is computed here, so a row costs one
         *     contract's worth of payload instead of all its items, and every client agrees on
         *     what the row says.
         *
         *     `status` and `date_completed` are deliberately absent. Both are fields of ESI's
         *     AUTHENTICATED character/corporation contract routes; the public route Hangar Bay
         *     reads carries neither, so the columns behind them hold a placeholder and a NULL for
         *     every contract in the corpus today. The columns stay — they fill in the moment a
         *     user's own contracts are ingested — but a wire field that can only misinform is
         *     worse than no wire field (ESI-3).
         */
        ContractListItemSchema: {
            blueprint_summary?: components["schemas"]["BlueprintSummary"] | null;
            /** Buyout */
            buyout?: number | null;
            /** Collateral */
            collateral: number;
            composition?: components["schemas"]["CompositionSummary"] | null;
            /** Contract Id */
            contract_id: number;
            /**
             * Date Expired
             * Format: date-time
             */
            date_expired: string;
            /**
             * Date Issued
             * Format: date-time
             */
            date_issued: string;
            /** Days To Complete */
            days_to_complete?: number | null;
            /** End Location Id */
            end_location_id?: number | null;
            /** End Location Name */
            end_location_name?: string | null;
            /** For Corporation */
            for_corporation: boolean;
            /** Is Blueprint Copy Contract */
            is_blueprint_copy_contract: boolean;
            /** Is Ship Contract */
            is_ship_contract: boolean;
            /** Issuer Corporation Id */
            issuer_corporation_id: number;
            /** Issuer Corporation Name */
            issuer_corporation_name?: string | null;
            /** Issuer Id */
            issuer_id: number;
            /** Issuer Name */
            issuer_name?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Price */
            price?: number | null;
            /** Primary Label */
            primary_label: string;
            /** Reward */
            reward?: number | null;
            /** Reward Per Volume */
            reward_per_volume?: number | null;
            /** Start Location Id */
            start_location_id?: number | null;
            /** Start Location Name */
            start_location_name?: string | null;
            /** Start Location System Id */
            start_location_system_id?: number | null;
            /** Title */
            title?: string | null;
            /** Type */
            type: string;
            /** Volume */
            volume?: number | null;
        };
        /**
         * ContractListResponse
         * @description A page of contracts plus the figures that make the page readable in context.
         *
         *     A bare total hides that system_ids can only ever match the locations we resolved:
         *     a search returning 3 results reads as "there are 3" when it may mean "there are 3
         *     we can place, and 40 more we cannot". Publishing the residual next to the number
         *     is the convention the EVE tooling ecosystem already uses for partial data —
         *     Adam4EVE prints a NoP (number of participants) column beside its aggregates,
         *     EVE Tycoon labels each row with the appraisal method behind it.
         */
        ContractListResponse: {
            /** @description Which regions the corpus actually holds and how fresh they are. Independent of the filters on this request — it describes the dataset, not the page, so a client can tell an uncovered region apart from a covered one that matched nothing. */
            coverage: components["schemas"]["CoverageInfo"];
            /**
             * Items
             * @description List of items for the current page
             */
            items: components["schemas"]["ContractListItemSchema"][];
            /**
             * Page
             * @description Current page number
             */
            page: number;
            /**
             * Segment Counts
             * @description Matching contracts per contract type, keyed by every ContractType value including the ones nothing matched, so a client renders a stable set of segments. Counts are of distinct contracts and are computed with the contract_type filter lifted and every other filter applied, so a segment the reader is not on still reports what selecting it would show. A stored type outside the enum is counted under 'unknown'.
             */
            segment_counts: {
                [key: string]: number;
            };
            /**
             * Size
             * @description Number of items per page
             */
            size: number;
            /**
             * Total
             * @description Total number of items
             */
            total: number;
            /**
             * Unknown System Excluded
             * @description How many contracts matched every other filter but were excluded because their start location has no known solar system (player-owned structures, which need an ACL-scoped token to resolve). Null when system_ids was not applied — no results were dropped for that reason, which is different from none having been.
             */
            unknown_system_excluded?: number | null;
        };
        /**
         * ContractType
         * @description Every contract type ESI can emit (confirmed against the committed spec
         *     snapshot). Typed as an enum so an unknown value 422s instead of silently
         *     matching nothing — the defect class this feature exists to remove (§17.8).
         * @enum {string}
         */
        ContractType: "item_exchange" | "auction" | "courier" | "loan" | "unknown";
        /**
         * CoverageInfo
         * @description Which regions the corpus actually holds, and how fresh the newest of them is.
         *
         *     Reported from observed rows rather than from the configured ingestion targets: the
         *     two diverge for the whole ingestion window after a coverage change, and during that
         *     window the configured value names a region holding nothing. A client that cannot
         *     read this has to either embed a region literal — wrong the day coverage expands —
         *     or infer coverage from an empty result, which reads a genuinely empty covered
         *     region as uncovered.
         */
        CoverageInfo: {
            /**
             * As Of
             * @description The newest ingestion stamp across all covered regions. Null when nothing is ingested, and also when nothing carries a stamp yet — absence of a freshness signal, not a claim of freshness at the epoch.
             */
            as_of?: string | null;
            /**
             * Ingested Region Ids
             * @description Every region id the contract corpus holds rows for, ascending. Empty before the first ingestion run completes.
             */
            ingested_region_ids: number[];
        };
        /** CurrentUserSchema */
        CurrentUserSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
        };
        /**
         * ErrorDetail
         * @description The FastAPI HTTPException / JSONResponse error body shape ({"detail": ...}),
         *     declared so the login/callback 400 and 503 responses carry their real JSON
         *     body in the OpenAPI contract instead of an empty one.
         */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NotificationSchema */
        NotificationSchema: {
            /** Contract Id */
            contract_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Read */
            is_read: boolean;
            /** Message */
            message: string;
            /** Price */
            price?: number | null;
            /** Type */
            type: string;
            /** Watch Type Id */
            watch_type_id?: number | null;
        };
        /** NotificationSettingsSchema */
        NotificationSettingsSchema: {
            /** Watchlist Alerts Enabled */
            watchlist_alerts_enabled: boolean;
        };
        /** PaginatedResponse[NotificationSchema] */
        PaginatedResponse_NotificationSchema_: {
            /**
             * Items
             * @description List of items for the current page
             */
            items: components["schemas"]["NotificationSchema"][];
            /**
             * Page
             * @description Current page number
             */
            page: number;
            /**
             * Size
             * @description Number of items per page
             */
            size: number;
            /**
             * Total
             * @description Total number of items
             */
            total: number;
        };
        /** SavedSearchCreate */
        SavedSearchCreate: {
            /** Name */
            name: string;
            search_parameters: components["schemas"]["SavedSearchParameters"];
        };
        /**
         * SavedSearchParameters
         * @description Server-side validation model for a saved search's stored filter blob. Mirrors the
         *     frontend ContractSearch shape minus `page`; extra="forbid" rejects the wire-only
         *     `is_ship_contract`, `page`, and arbitrary junk (design §4.5). The type, taxonomy, and
         *     blueprint-attribute filters are held here because the contracts query honours them; their
         *     bounds match ContractFilters so a saved blob can never replay into a 422.
         */
        SavedSearchParameters: {
            /** Category Id */
            category_id?: number[] | null;
            /** Contract Type */
            contract_type?: components["schemas"]["ContractType"][] | null;
            /** Group Id */
            group_id?: number[] | null;
            /** Is Bpc */
            is_bpc?: boolean | null;
            /** Max Me */
            max_me?: number | null;
            /** Max Price */
            max_price?: number | null;
            /** Max Runs */
            max_runs?: number | null;
            /** Max Te */
            max_te?: number | null;
            /** Min Me */
            min_me?: number | null;
            /** Min Price */
            min_price?: number | null;
            /** Min Runs */
            min_runs?: number | null;
            /** Min Te */
            min_te?: number | null;
            /** Region Ids */
            region_ids?: number[] | null;
            /** Search */
            search?: string | null;
            /**
             * Ships Only
             * @default true
             */
            ships_only: boolean;
            /**
             * Size
             * @default 50
             */
            size: number;
            /** @default date_issued */
            sort_by: components["schemas"]["SortableContractFields"];
            /** @default desc */
            sort_direction: components["schemas"]["SortDirection"];
        };
        /** SavedSearchSchema */
        SavedSearchSchema: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            search_parameters: components["schemas"]["SavedSearchParameters"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SavedSearchUpdate */
        SavedSearchUpdate: {
            /** Name */
            name: string;
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: "asc" | "desc";
        /**
         * SortableContractFields
         * @description Fields that can be used for sorting contracts.
         * @enum {string}
         */
        SortableContractFields: "date_issued" | "date_expired" | "price" | "collateral" | "ship_name" | "volume" | "reward_per_volume" | "days_to_complete" | "buyout";
        /**
         * TaxonomyCategory
         * @description One dogma category the filter rail can offer.
         */
        TaxonomyCategory: {
            /** Category Id */
            category_id: number;
            /** Name */
            name: string;
        };
        /**
         * TaxonomyCoverage
         * @description Whether the item-level surface can be opened yet.
         *
         *     "complete" means the corpus is enriched at the current enrichment version AND the
         *     name cache names every category that corpus holds. Anything short of both is
         *     "partial": a taxonomy filter offered over half-enriched items returns a page that
         *     is missing contracts for reasons the reader cannot see, which is worse than a
         *     control that is honestly not ready. Degrades on its own during any future
         *     enrichment resweep and restores on its own afterwards.
         * @enum {string}
         */
        TaxonomyCoverage: "partial" | "complete";
        /**
         * TaxonomyGroup
         * @description One dogma group, carrying the category it belongs to so the client can scope
         *     the group list to the selected categories without a second request.
         */
        TaxonomyGroup: {
            /** Category Id */
            category_id?: number | null;
            /** Group Id */
            group_id: number;
            /** Name */
            name: string;
        };
        /**
         * TaxonomyResponse
         * @description The option lists behind the category and group filters, plus their readiness.
         *
         *     Flat rather than nested (§17.6): the client filters groups down to the selected
         *     categories locally, so changing a category selection costs no round trip.
         */
        TaxonomyResponse: {
            /**
             * Categories
             * @description Every cached dogma category, ascending by name.
             */
            categories: components["schemas"]["TaxonomyCategory"][];
            /** @description Whether the item-level filters can be trusted yet, measured from observed rows: 'complete' only when the live corpus is enriched at the current enrichment version and every category on its items has a cached name. 'partial' while either is still true, including on a cold cache. */
            coverage: components["schemas"]["TaxonomyCoverage"];
            /**
             * Groups
             * @description Every cached dogma group, ascending by name, each naming its category so the client can scope the list without refetching.
             */
            groups: components["schemas"]["TaxonomyGroup"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchlistItemCreate
         * @description Add-watchlist body: exactly one of type_id / type_name, plus optional max_price / notes.
         */
        WatchlistItemCreate: {
            /**
             * Max Price
             * @description ISK; >= 0.01 when present.
             */
            max_price?: number | null;
            /** Notes */
            notes?: string | null;
            /** Type Id */
            type_id?: number | null;
            /** Type Name */
            type_name?: string | null;
        };
        /** WatchlistItemSchema */
        WatchlistItemSchema: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Max Price */
            max_price?: number | null;
            /** Notes */
            notes?: string | null;
            /** Type Id */
            type_id: number;
            /** Type Name */
            type_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WatchlistItemUpdate
         * @description Partial update: omitted field preserves, explicit JSON null clears (via model_fields_set).
         */
        WatchlistItemUpdate: {
            /** Max Price */
            max_price?: number | null;
            /** Notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_auth_sso_callback_get: {
        parameters: {
            query?: {
                state?: string | null;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SSO state/browser-binding mismatch. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description EVE SSO is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    login_auth_sso_login_get: {
        parameters: {
            query?: {
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description EVE SSO is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    logout_auth_sso_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_public_contracts_contracts__get: {
        parameters: {
            query?: {
                /** @description Case-insensitive search across contract title and ship name. */
                search?: string | null;
                /** @description Minimum price. */
                min_price?: number | null;
                /** @description Maximum price. */
                max_price?: number | null;
                /** @description Minimum collateral. */
                min_collateral?: number | null;
                /** @description Maximum collateral. */
                max_collateral?: number | null;
                /** @description Minimum runs for BPCs. Matches contracts with at least one offered item satisfying every bound in this family. */
                min_runs?: number | null;
                /** @description Maximum runs for BPCs. Matches contracts with at least one offered item satisfying every bound in this family. */
                max_runs?: number | null;
                /** @description Minimum Material Efficiency for BPCs. Matches contracts with at least one offered item satisfying every bound in this family. */
                min_me?: number | null;
                /** @description Maximum Material Efficiency for BPCs. Matches contracts with at least one offered item satisfying every bound in this family. */
                max_me?: number | null;
                /** @description Minimum Time Efficiency for BPCs. Matches contracts with at least one offered item satisfying every bound in this family. */
                min_te?: number | null;
                /** @description Maximum Time Efficiency for BPCs. Matches contracts with at least one offered item satisfying every bound in this family. */
                max_te?: number | null;
                /** @description List of region IDs to filter by. */
                region_ids?: number[] | null;
                /** @description List of solar system IDs to filter by. Partial coverage: contracts in NPC stations carry a resolved system, contracts in player-owned structures do not and never match. The response's unknown_system_excluded field reports how many results were dropped for that reason. */
                system_ids?: number[] | null;
                /** @description List of station IDs to filter by. */
                station_ids?: number[] | null;
                /** @description List of ship type IDs to filter by. */
                type_ids?: number[] | null;
                /** @description Contract types to include (repeatable). */
                contract_type?: components["schemas"]["ContractType"][] | null;
                /** @description Dogma category ids; matches contracts with at least one offered item in any of them. */
                category_id?: number[] | null;
                /** @description Dogma group ids, scoped within category_id when both are set (same offered item satisfies both). */
                group_id?: number[] | null;
                /** @description Filter for contracts containing blueprints (BPCs). */
                is_bpc?: boolean | null;
                /** @description Filter for contracts flagged as ship contracts (contract-level flag). */
                is_ship_contract?: boolean | null;
                /** @description Page number. */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
                /** @description Field to sort by. */
                sort_by?: components["schemas"]["SortableContractFields"];
                /** @description Sort direction. */
                sort_direction?: components["schemas"]["SortDirection"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contract_taxonomy_contracts_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyResponse"];
                };
            };
        };
    };
    get_contract_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserSchema"];
                };
            };
        };
    };
    get_notification_settings_me_notification_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    update_notification_settings_me_notification_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettingsSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_me_notifications__get: {
        parameters: {
            query?: {
                is_read?: boolean | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_NotificationSchema_"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_me_notifications_mark_all_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    mark_read_me_notifications__notification_id__mark_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_searches_me_saved_searches__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    create_saved_search_me_saved_searches__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"];
                };
            };
            /** @description Per-user saved-search cap reached */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Duplicate saved-search name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_saved_search_me_saved_searches__search_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Saved search not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Duplicate saved-search name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_search_me_saved_searches__search_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Saved search not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_items_me_watchlist_items__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemSchema"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    add_watchlist_item_me_watchlist_items__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemSchema"];
                };
            };
            /** @description Cap reached / unknown name / not a published ship */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Already watching this type */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description ESI unreachable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    update_watchlist_item_me_watchlist_items__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemSchema"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_item_me_watchlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
