/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_auth_sso_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_sso_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_sso_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cache Test
         * @description Temporary endpoint to test cache connectivity and basic operations.
         */
        get: operations["cache_test_cache_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Public Contracts
         * @description Retrieves a paginated list of contracts based on specified filters.
         *
         *     This endpoint uses a service layer to apply advanced filtering, sorting,
         *     and pagination to public contracts.
         */
        get: operations["list_public_contracts_contracts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract
         * @description Retrieves a single contract by its ID, including its items.
         */
        get: operations["get_contract_contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContractItemSchema
         * @description Schema for an item within a contract.
         */
        ContractItemSchema: {
            /** Category */
            category?: string | null;
            /** Is Blueprint Copy */
            is_blueprint_copy?: boolean | null;
            /** Is Included */
            is_included: boolean;
            /** Is Singleton */
            is_singleton: boolean;
            /** Market Group Id */
            market_group_id?: number | null;
            /** Quantity */
            quantity: number;
            /** Raw Quantity */
            raw_quantity?: number | null;
            /** Record Id */
            record_id: number;
            /** Type Id */
            type_id: number;
            /** Type Name */
            type_name?: string | null;
        };
        /**
         * ContractSchema
         * @description Schema for a public contract.
         */
        ContractSchema: {
            /** Contract Id */
            contract_id: number;
            /** Date Completed */
            date_completed?: string | null;
            /**
             * Date Expired
             * Format: date-time
             */
            date_expired: string;
            /**
             * Date Issued
             * Format: date-time
             */
            date_issued: string;
            /** End Location Id */
            end_location_id?: number | null;
            /** For Corporation */
            for_corporation: boolean;
            /** Is Ship Contract */
            is_ship_contract: boolean;
            /** Issuer Corporation Id */
            issuer_corporation_id: number;
            /** Issuer Corporation Name */
            issuer_corporation_name?: string | null;
            /** Issuer Id */
            issuer_id: number;
            /** Issuer Name */
            issuer_name?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ContractItemSchema"][];
            /** Price */
            price?: number | null;
            /** Reward */
            reward?: number | null;
            /** Start Location Id */
            start_location_id: number;
            /** Start Location Name */
            start_location_name?: string | null;
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
            /** Type */
            type: string;
            /** Volume */
            volume?: number | null;
        };
        /** CurrentUserSchema */
        CurrentUserSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedResponse[ContractSchema] */
        PaginatedResponse_ContractSchema_: {
            /**
             * Items
             * @description List of items for the current page
             */
            items: components["schemas"]["ContractSchema"][];
            /**
             * Page
             * @description Current page number
             */
            page: number;
            /**
             * Size
             * @description Number of items per page
             */
            size: number;
            /**
             * Total
             * @description Total number of items
             */
            total: number;
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: "asc" | "desc";
        /**
         * SortableContractFields
         * @description Fields that can be used for sorting contracts.
         * @enum {string}
         */
        SortableContractFields: "date_issued" | "date_expired" | "price" | "collateral" | "ship_name" | "volume";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_auth_sso_callback_get: {
        parameters: {
            query?: {
                state?: string | null;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description SSO state/browser-binding mismatch. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description EVE SSO is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_auth_sso_login_get: {
        parameters: {
            query?: {
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_sso_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cache_test_cache_test_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_public_contracts_contracts__get: {
        parameters: {
            query?: {
                /** @description Case-insensitive search across contract title and ship name. */
                search?: string | null;
                /** @description Minimum price. */
                min_price?: number | null;
                /** @description Maximum price. */
                max_price?: number | null;
                /** @description Minimum collateral. */
                min_collateral?: number | null;
                /** @description Maximum collateral. */
                max_collateral?: number | null;
                /** @description Minimum runs for BPCs (-1 for original). */
                min_runs?: number | null;
                /** @description Maximum runs for BPCs. */
                max_runs?: number | null;
                /** @description Minimum Material Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                min_me?: number | null;
                /** @description Maximum Material Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                max_me?: number | null;
                /** @description Minimum Time Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                min_te?: number | null;
                /** @description Maximum Time Efficiency for BPCs. (NOT IMPLEMENTED — accepted but ignored by the service; do not expose in clients) */
                max_te?: number | null;
                /** @description List of region IDs to filter by. */
                region_ids?: number[] | null;
                /** @description List of solar system IDs to filter by. */
                system_ids?: number[] | null;
                /** @description List of station IDs to filter by. */
                station_ids?: number[] | null;
                /** @description List of ship type IDs to filter by. */
                type_ids?: number[] | null;
                /** @description Filter for contracts containing blueprints (BPCs). */
                is_bpc?: boolean | null;
                /** @description Filter for contracts flagged as ship contracts (contract-level flag). */
                is_ship_contract?: boolean | null;
                /** @description Page number. */
                page?: number;
                /** @description Number of items per page. */
                size?: number;
                /** @description Field to sort by. */
                sort_by?: components["schemas"]["SortableContractFields"];
                /** @description Sort direction. */
                sort_direction?: components["schemas"]["SortDirection"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ContractSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserSchema"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
