/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'

const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/': typeof ContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts': typeof ContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/': typeof ContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/saved-searches' | '/contracts/$contractId' | '/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/saved-searches' | '/contracts/$contractId' | '/contracts'
  id:
    | '__root__'
    | '/'
    | '/saved-searches'
    | '/contracts/$contractId'
    | '/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  ContractsIndexRoute: ContractsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
