"""baseline

Revision ID: 3aca702a74e3
Revises: 
Create Date: 2026-07-18 20:11:31.941383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aca702a74e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('contract_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('collateral', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('issuer_corporation_id', sa.Integer(), nullable=False),
    sa.Column('start_location_id', sa.BigInteger(), nullable=True),
    sa.Column('start_location_system_id', sa.Integer(), nullable=True),
    sa.Column('start_location_region_id', sa.Integer(), nullable=True),
    sa.Column('end_location_id', sa.BigInteger(), nullable=True),
    sa.Column('for_corporation', sa.Boolean(), nullable=False),
    sa.Column('date_issued', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_expired', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('start_location_name', sa.String(), nullable=True),
    sa.Column('issuer_name', sa.String(), nullable=True),
    sa.Column('issuer_corporation_name', sa.String(), nullable=True),
    sa.Column('is_ship_contract', sa.Boolean(), nullable=False),
    sa.Column('item_processing_status', sa.String(), nullable=False),
    sa.Column('items_last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_esi_etag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index('ix_contracts_collateral', 'contracts', ['collateral'], unique=False)
    op.create_index('ix_contracts_date_issued', 'contracts', ['date_issued'], unique=False)
    op.create_index('ix_contracts_is_ship_contract', 'contracts', ['is_ship_contract'], unique=False)
    op.create_index(op.f('ix_contracts_item_processing_status'), 'contracts', ['item_processing_status'], unique=False)
    op.create_index('ix_contracts_price', 'contracts', ['price'], unique=False)
    op.create_index('ix_contracts_start_location_name', 'contracts', ['start_location_name'], unique=False)
    op.create_index('ix_contracts_title', 'contracts', ['title'], unique=False)
    op.create_index('ix_contracts_type_status', 'contracts', ['type', 'status'], unique=False)
    op.create_index('ix_contracts_volume', 'contracts', ['volume'], unique=False)
    op.create_table('esi_market_group_cache',
    sa.Column('market_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('raw_esi_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['esi_market_group_cache.market_group_id'], ),
    sa.PrimaryKeyConstraint('market_group_id')
    )
    op.create_index('ix_esi_market_group_cache_parent_group_id', 'esi_market_group_cache', ['parent_group_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('owner_hash', sa.String(length=255), nullable=False),
    sa.Column('esi_access_token', sa.Text(), nullable=True),
    sa.Column('esi_access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('esi_refresh_token', sa.Text(), nullable=True),
    sa.Column('esi_scopes', sa.Text(), nullable=True),
    sa.Column('watchlist_alerts_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_character_id'), 'users', ['character_id'], unique=True)
    op.create_index(op.f('ix_users_owner_hash'), 'users', ['owner_hash'], unique=False)
    op.create_table('contract_items',
    sa.Column('record_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('is_blueprint_copy', sa.Boolean(), nullable=True),
    sa.Column('raw_quantity', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('ix_contract_items_contract_id', 'contract_items', ['contract_id'], unique=False)
    op.create_index('ix_contract_items_is_blueprint_copy', 'contract_items', ['is_blueprint_copy'], unique=False)
    op.create_index('ix_contract_items_raw_quantity', 'contract_items', ['raw_quantity'], unique=False)
    op.create_index('ix_contract_items_type_id', 'contract_items', ['type_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('watch_type_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('uq_notifications_watchlist_dedup', 'notifications', ['user_id', 'contract_id', 'watch_type_id'], unique=True, postgresql_where=sa.text("type = 'watchlist_match'"))
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('search_parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_searches_user_name')
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type_id', name='uq_watchlist_items_user_type')
    )
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index('uq_notifications_watchlist_dedup', table_name='notifications', postgresql_where=sa.text("type = 'watchlist_match'"))
    op.drop_index('ix_notifications_user_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_contract_items_type_id', table_name='contract_items')
    op.drop_index('ix_contract_items_raw_quantity', table_name='contract_items')
    op.drop_index('ix_contract_items_is_blueprint_copy', table_name='contract_items')
    op.drop_index('ix_contract_items_contract_id', table_name='contract_items')
    op.drop_table('contract_items')
    op.drop_index(op.f('ix_users_owner_hash'), table_name='users')
    op.drop_index(op.f('ix_users_character_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_esi_market_group_cache_parent_group_id', table_name='esi_market_group_cache')
    op.drop_table('esi_market_group_cache')
    op.drop_index('ix_contracts_volume', table_name='contracts')
    op.drop_index('ix_contracts_type_status', table_name='contracts')
    op.drop_index('ix_contracts_title', table_name='contracts')
    op.drop_index('ix_contracts_start_location_name', table_name='contracts')
    op.drop_index('ix_contracts_price', table_name='contracts')
    op.drop_index(op.f('ix_contracts_item_processing_status'), table_name='contracts')
    op.drop_index('ix_contracts_is_ship_contract', table_name='contracts')
    op.drop_index('ix_contracts_date_issued', table_name='contracts')
    op.drop_index('ix_contracts_collateral', table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
