"""Add contract, item, and market group models

Revision ID: c199a09ccc55
Revises: baa67b53c016
Create Date: 2025-06-10 05:29:41.515629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c199a09ccc55'
down_revision: Union[str, None] = 'baa67b53c016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('contract_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('issuer_corporation_id', sa.Integer(), nullable=False),
    sa.Column('start_location_id', sa.BigInteger(), nullable=False),
    sa.Column('end_location_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('for_corporation', sa.Boolean(), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=False),
    sa.Column('date_expired', sa.DateTime(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('start_location_name', sa.String(), nullable=True),
    sa.Column('issuer_name', sa.String(), nullable=True),
    sa.Column('issuer_corporation_name', sa.String(), nullable=True),
    sa.Column('is_ship_contract', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index('ix_contracts_is_ship_contract', 'contracts', ['is_ship_contract'], unique=False)
    op.create_index('ix_contracts_start_location_name', 'contracts', ['start_location_name'], unique=False)
    op.create_index('ix_contracts_title', 'contracts', ['title'], unique=False)
    op.create_index('ix_contracts_type_status', 'contracts', ['type', 'status'], unique=False)
    op.create_table('esi_market_group_cache',
    sa.Column('market_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('raw_esi_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['esi_market_group_cache.market_group_id'], ),
    sa.PrimaryKeyConstraint('market_group_id')
    )
    op.create_index('ix_esi_market_group_cache_parent_group_id', 'esi_market_group_cache', ['parent_group_id'], unique=False)
    op.create_table('contract_items',
    sa.Column('record_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('raw_quantity', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('ix_contract_items_contract_id', 'contract_items', ['contract_id'], unique=False)
    op.create_index('ix_contract_items_type_id', 'contract_items', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contract_items_type_id', table_name='contract_items')
    op.drop_index('ix_contract_items_contract_id', table_name='contract_items')
    op.drop_table('contract_items')
    op.drop_index('ix_esi_market_group_cache_parent_group_id', table_name='esi_market_group_cache')
    op.drop_table('esi_market_group_cache')
    op.drop_index('ix_contracts_type_status', table_name='contracts')
    op.drop_index('ix_contracts_title', table_name='contracts')
    op.drop_index('ix_contracts_start_location_name', table_name='contracts')
    op.drop_index('ix_contracts_is_ship_contract', table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
