// Regenerates src/features/contracts/regions.ts from ESI (public, no auth).
// Run: node scripts/generate-regions.mjs
// Pin an explicit ESI route version (matches the backend ESIClient convention);
// /latest is soft-deprecated and unversioned aliases are what ESI's spring-cleaning removes.
const ESI = 'https://esi.evetech.net/v1'

const ids = await (await fetch(`${ESI}/universe/regions/`)).json()
// K-space regions only: wormhole (11xxxxxx) and abyssal (12xxxxxx+) regions
// never host public contracts a marketplace user can reach.
const kspace = ids.filter((id) => id < 11000000)
const regions = await Promise.all(
  kspace.map(async (id) => {
    const region = await (await fetch(`${ESI}/universe/regions/${id}/`)).json()
    return { id, name: region.name }
  }),
)
regions.sort((a, b) => a.name.localeCompare(b.name))

const lines = regions.map((r) => `  { id: ${r.id}, name: ${JSON.stringify(r.name)} },`)
const content = `// GENERATED by scripts/generate-regions.mjs — do not edit by hand.
// EVE region IDs are stable static data; regenerate only if CCP adds regions.
export const REGIONS = [
${lines.join('\n')}
] as const

export type Region = (typeof REGIONS)[number]
`
await (await import('node:fs/promises')).writeFile('src/features/contracts/regions.ts', content)
console.log(`Wrote ${regions.length} regions`)
